// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyRmVX-ARDWci2Suux0_YB6atuYXG4EJc',
    appId: '1:69795892359:web:83c3532507aa054ce0fc22',
    messagingSenderId: '69795892359',
    projectId: 'step-in-style',
    authDomain: 'step-in-style.firebaseapp.com',
    storageBucket: 'step-in-style.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOPEJYZtCZfaDNojknwXYSbO1afbke9k',
    appId: '1:69795892359:android:d94089df763e6d70e0fc22',
    messagingSenderId: '69795892359',
    projectId: 'step-in-style',
    storageBucket: 'step-in-style.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCavYIfAhK_VEuHUEFzsUdL3DhElDZp924',
    appId: '1:69795892359:ios:a776c4f26140b79ce0fc22',
    messagingSenderId: '69795892359',
    projectId: 'step-in-style',
    storageBucket: 'step-in-style.appspot.com',
    androidClientId: '69795892359-v70gs1h1sqk4ad21eub5tajkh9u23fne.apps.googleusercontent.com',
    iosClientId: '69795892359-33221aftrsnnn6cnha8af0r567j1rb1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepInStyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCavYIfAhK_VEuHUEFzsUdL3DhElDZp924',
    appId: '1:69795892359:ios:c17b20480d2fc0b9e0fc22',
    messagingSenderId: '69795892359',
    projectId: 'step-in-style',
    storageBucket: 'step-in-style.appspot.com',
    androidClientId: '69795892359-v70gs1h1sqk4ad21eub5tajkh9u23fne.apps.googleusercontent.com',
    iosClientId: '69795892359-k9mrrv8uoq88aebe6rm9bj79adbk4t02.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepInStyle.RunnerTests',
  );
}
